config/routes.rb
class SSConstraint
  def matches?(request)
    request.host().include?("schoolsafari") || request.host().include?("crzy")
  end
end

class BRConstraint
  def matches?(request)
    !request.host().include?("schoolsafari") && !request.host().include?("crzy")
  end
end

require 'api_constraints'
require 'routes/constraints/subcategories'

Rails.application.routes.draw do

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, :at => '/store_admin'
        
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :operators
  resources :competitions

  resources :posts do
    collection do
      get 'all_posts'
      get 'paginate'
    end
    member     { get 'paginate_place_to_visit' }
    resources :places, controller: :places_posts
    resources :countries, controller: :countries_posts
    resources :subcategories, controller: :posts_subcategories
  end

  resources :stories do
    collection do
      get 'paginate'
      post 'featured'
      get 'feed'
      get 'wp_feed'
    end
    member do
      get 'seo_analysis'
      get 'paginate_place'
      post :upload_image
      post :delete_image
    end
    resources :photos do
      collection { get 'choose_hero', as: :choose_hero }
    end
    resources :places, controller: :places_stories
    resources :attractions, controller: :attractions_stories
    resources :regions, controller: :regions_stories
    resources :countries, controller: :countries_stories
    resources :subcategories, controller: :stories_subcategories
  end

  post 'stories/autosave', as: :autosave_story_path

  get 'stories_all' => 'stories#index_new'

  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine => '/apidoc'

  resources :bug_posts

  mount Ckeditor::Engine => '/ckeditor'
  post '/rate' => 'rater#create', :as => 'rate'
  constraints(SSConstraint.new) do
    get '/', to: 'places#programsearch', as: nil
  end

  constraints(BRConstraint.new) do
    get '/', to: 'pages#index', as: :root
  end

  get 'pages/terms' => 'pages#terms'
  get 'pages/privacy' => 'pages#privacy'
  get '/robots.txt' => 'pages#robots'

  resources :transactions

  resources :custom_reports do
    collection { get "photo_errors" }
  end

  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq'

  mount RailsAdmin::Engine => '/admin/info', as: 'rails_admin'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  mount Soulmate::Server, at: "/sm"

  mount ConfigurableEngine::Engine => '/admin/configurable', as: 'configurable'

  get 'terms-conditions' => 'posts#show', :defaults => { :id => 'terms-conditions' }
  get 'booking-guarantee' => 'posts#show', :defaults => { :id => 'booking-guarantee' }
  get 'frequently-asked-questions' => 'posts#show', :defaults => { :id => 'frequently-asked-questions' }
  get 'about-us' => 'posts#show', :defaults => { :id => 'about-us' }
  get 'privacy' => 'posts#show', :defaults => { :id => 'privacy' }

  get 'factual_places/search' => 'factual_places#search'

  get 'results' => 'search_suggestions#index', as: 'searching'
  get 'results/:sub_cat_id' => 'search_suggestions#index', as: 'searching_sub_cat'
  get 'nearby' => 'search_suggestions#nearby', as: 'searching_nearby'

  post 'searchqueries/create' => 'search_queries#create'
  post 'pages/want_notification' => 'pages#want_notification'
  get "areas/mapdata" => "areas#mapdata"
  get "areas/search" => "areas#search"
  get "places/mapdata" => "places#mapdata"
  get "places/placeareasmapdata" => "places#placeareasmapdata"
  get "places/search" => "places#search"
  get "places/subcategory_match_test" => "places#subcategory_match_test"
  get "places/subcategory_match" => "places#subcategory_match"
  get "places/liked_places" => "places#liked_places"
  get "places/tags" => "places#tags"
  get "programs/tags" => "programs#tags"

  get "places/publishing_queue" => "places#publishing_queue"

  get "places/debug" => 'places#debug'
  get "places/programsearch" => 'places#programsearch' #xyrin index.html
  get "places/placeprograms" => 'places#placeprograms' #xyrin result.html
  get "places/programsearchresultslist" => 'places#programsearchresultslist' #xyrin search.html
  get "places/programsearchresultsmap" => 'places#programsearchresultsmap' #xyrin map.html

  get "/sitemap" => redirect("https://s3-ap-southeast-2.amazonaws.com/mydiscoveries/sitemaps/sitemap.xml.gz")

  post 'fun_facts_users/create' => 'fun_facts_users#create'
  post 'fun_facts_users/destroy' => 'fun_facts_users#destroy'
  post 'photos_users/create' => 'photos_users#create'
  post 'photos_users/destroy' => 'photos_users#destroy'
  post 'places_users/create' => 'places_users#create'
  post 'places_users/destroy' => 'places_users#destroy'
  post 'attractions_users/create' => 'attractions_users#create'
  post 'attractions_users/destroy' => 'attractions_users#destroy'
  post 'regions_users/create' => 'regions_users#create'
  post 'regions_users/destroy' => 'regions_users#destroy'
  post 'offers_users/create' => 'offers_users#create'
  post 'offers_users/destroy' => 'offers_users#destroy'
  post 'countries_users/create' => 'countries_users#create'
  post 'countries_users/destroy' => 'countries_users#destroy'
  post 'videos_users/create' => 'videos_users#create'
  post 'videos_users/destroy' => 'videos_users#destroy'
  post 'user_photos_users/create' => 'user_photos_users#create'
  post 'user_photos_users/destroy' => 'user_photos_users#destroy'
  post 'stories_users/create' => 'stories_users#create'
  post 'stories_users/destroy' => 'stories_users#destroy'
  post 'reviews_users/create' => 'reviews_users#create'
  post 'reviews_users/destroy' => 'reviews_users#destroy'
  post 'posts_users/create' => 'posts_users#create'
  post 'posts_users/destroy' => 'posts_users#destroy'

  resources :user_photos do
    member { put 'place_update' }
  end
  post 'user_photos/profile_create' => 'user_photos#profile_create'

  get 'stamp_transactions/stamp_here' => 'stamp_transactions#stamp_here'
  get 'stamp_transactions/stamp_error' => 'stamp_transactions#stamp_error'
  resources :stamp_transactions

  devise_for :users, controllers: {
    passwords:          'passwords',
    registrations:      'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions:           'sessions',
    confirmations:      'confirmations'
  }

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get '/users/sign_out' => 'devise/sessions#destroy'
    put 'users/:id' => 'users#update'
    post '/update_password_user' =>  'users/user_password#update_password'
  end

  resources :pages do
    collection do 
      get 'all_pages'
      get :wp_feed
    end
    member { get 'paginate_places'}
    member { get 'paginate_stories'}
    member { get 'paginate_offers'}
  end

  get '/google_map_home' => 'pages#google_map_home'

  get '/puzzles/:action' => 'puzzles#:action'

  get '/users/videos' => 'users#videos'
  get '/users/places' => 'users#places'
  get '/users/fun_facts' => 'users#fun_facts'
  get '/users/instagram_feed' => 'users#instagram_feed'
  get '/users/draft_content' => 'users#draft_content' # All User Uploaded Content in Draft

  resources :users do
    collection do
      get 'leaderboard'
      post 'confirm'
    end
    member do
      get 'paginate_stories'
      get 'paginate_favorite_stories'
      get 'paginate_places'
      get 'paginate_offers'
      get 'paginate_regions'
      get 'paginate_place_to_visit'
      get 'favourites'
      get 'paginate_reviews'
      get 'paginate_photos'
      get 'paginate_orders'
      get 'photos'
      get 'reviews'
      get 'stories'
      get 'public_profile'
    end
  end
  resources :landings



  resources :three_d_videos

  resources :photos do
    collection { post :import }
    member { put 'place_update' }
    member { put 'attraction_update' }
    member { put 'region_update' }
    member { put 'story_update' }
    member { put 'country_update' }
    member { put 'offer_update' }
  end

  resources :videos do
    collection { post :import }
  end

  resources :programs do
    resources :webresources
    collection { post :import }
    collection { post :validate_import }
  end

  resources :discounts

  resources :fun_facts do
    collection { post :import }
  end

  resources :countries do
    member do
      get 'paginate_videos', as: :paginate_videos
      get 'paginate_photos', as: :paginate_photos
      get 'paginate_stories'
      get 'paginate_things_to_do'
      get 'paginate_deals'
      get 'seo_analysis'
    end
    resources :good_to_knows
    resources :stories
    resources :deals
    resources :info_bits do
      collection { get 'all' }
    end
    resources :videos do
      collection { get 'all' }
    end
    resources :famous_faces do
      collection { get 'all' }
    end
    resources :photos do
      collection { get 'all_photos' }
      collection { get 'choose_hero', as: :choose_hero }
    end
    resources :fun_facts do
      collection { get 'all' }
    end
    collection { post :import }
  end

  resources :points_values

  match '/send_postcard', to: 'places#send_postcard', via: 'post'

  match '/send_user_story', to: 'users#send_story', via: 'post'

  match 'content_rejected', to: 'places#content_rejected', via: 'post'

  get '/virginaustralia', to: 'places#show', :defaults => {:id => 939}

  get "/users/username/new" => "users/accounts#forgot_username"
  post "/users/username/send_username" => "users/accounts#send_username"

  get "/wp-blog/:id/:place", to: "places#wp_blog"

  get "/primary_categories/cms_index", to: "primary_categories#cms_index"

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  include Searchable

  mount_uploader :hero_photo, PostHeroPhotoUploader

  before_update :regenerate_slug

  #scope :active, -> { where(status: "live") }

  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true
  validates :seo_friendly_url, presence: true

  friendly_id :slug_candidates, :use => :slugged

  belongs_to :user
  belongs_to :primary_category

  has_many :places_posts
  has_many :places, through: :places_posts

  has_many :attractions_posts
  has_many :posts, through: :attractions_posts

  has_many :posts_users
  has_many :users, through: :posts_users

  has_many :posts_subcategories
  has_many :subcategories, through: :posts_subcategories

  has_many :countries_posts
  has_many :countries, through: :countries_posts

  accepts_nested_attributes_for :places
  accepts_nested_attributes_for :countries

  def self.active
    where(status: "live")
  end

  def story_title
    html_title = Nokogiri::HTML::Document.parse self.title

    title = html_title.at_css('h2').text rescue ""
  end

  def story_images
    content = Nokogiri::HTML::Document.parse self.content

    images = content.css('img').map{ |image| image['src'] }
  end

  def self.all_active_posts
    Rails.cache.fetch("all_posts", expires_in: 12.hours) do
      Post.active.includes(:user).order(publish_date: :desc).order(created_at: :desc)
    end
  end

  def teaser
    string = ""
    content = Nokogiri::HTML::Document.parse self.content
    content.css('p').each do |paragraph|
      if !paragraph.content.blank?
        string += "<p>" + paragraph + "</p>"
      end
    end

    string = string[0..280] + "..."
  end

  def description

    text = Nokogiri::HTML::Document.parse content
    desc = text.search("//text()").map(&:text)
    result = ""
    desc.each do |paragraph|
      if paragraph.size > 20
        result = paragraph
        break
      end
    end

    result

  end

  def published?
    if self.status == "live"
      true
    else
      false
    end
  end

  private

  def slug_candidates
    :seo_friendly_url
  end

  def regenerate_slug
    if self.seo_friendly_url_changed?
      self.slug = seo_friendly_url.parameterize
    end
  end
end

app/helpers/attractions_helper.rb
module AttractionsHelper

  def found_in_parent(obj)
    parent_obj = obj.parent.parentable

    if parent_obj.class.to_s == 'Country'
      return link_to parent_obj.display_name, country_path(parent_obj), target: '_blank'
    elsif parent_obj.class.to_s == 'Place'
      return link_to parent_obj.display_name, place_path(parent_obj), target: '_blank'
    elsif parent_obj.class.to_s == 'Attraction'
      return link_to parent_obj.display_name, attraction_path(parent_obj), target: '_blank'
    end
  end

end

app/views/attractions/_admin_tabs.html.erb
<p class="top20">
  <a href="<%= attraction_path(@attraction) %>" class="btn btn-primary"
    target="_blank">View attraction Page</a>
  <a href="<%= attraction_good_to_knows_path(@attraction) %>"
    class="btn btn-primary" >Good To Knows</a>
  <a href="<%= choose_hero_attraction_photos_path(@attraction) %>"
    class="btn btn-primary">Edit / Add Photos</a>
  <a href="<%= polymorphic_path([@attraction, Deal]) %>"
    class="btn btn-primary">Deals</a>
  <a href="<%= all_attraction_videos_path(@attraction) %>"
    class="btn btn-primary">Videos</a>
  <a href="<%= attraction_three_d_videos_path(@attraction) %>"
    class="btn btn-primary" >3D Videos</a>
  <a href="<%= all_attraction_fun_facts_path(@attraction) %>"
    class="btn btn-primary">Fun Facts</a>
</p>

app/views/attractions/index.html.erb
<% if (user_signed_in?) && ( current_user.try(:admin) || current_user.has_role?("editor") || current_user.has_role?("publisher") ) %>
  <div id="table-container">
    <h1>All Attractions</h1>
    <table class="table table-striped" id="place-table">
      <thead>
        <tr>
          <th>Attraction</th>
          <th>Parent</th>
          <th>Word Count</th>
          <th>SEO Rating</th>
          <th>Edit Link</th>
          <th>Subscription Level</th>
          <th>Status</th>
          <th>Updated At</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th>Attraction</th>
          <th>Parent</th>
          <th>Word Count</th>
          <th></th>
          <th>Subscription Level</th>
          <th>Status</th>
          <th></th>
        </tr>
      </tfoot>
      <tbody>
        <% @attractions.each do |attraction| %>
          <tr>
            <td><%= link_to "#{attraction.display_name} || #{attraction.id}", edit_attraction_path(attraction) %></td>
            <td><%= attraction.parent.present? ? (attraction.parent.parentable.class.to_s+ ": " + attraction.parent.parentable.display_name rescue '') : "No Parent" %></td>
            <td><%= attraction.description.blank? ? 0 : (attraction.description.size / 6) %></td>
            <td><%= link_to attraction.seo_complete_percentage, seo_analysis_attraction_path(attraction) %></td>
            <td><%= link_to "Edit attraction", edit_attraction_path(attraction), target: "_blank" %></td>
            <td><%= attraction.subscription_level %></td>
            <td><%= attraction.status %></td>
            <td><%= attraction.updated_at.strftime('%F at %T') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <% if current_user.try(:admin) && current_user.email == "donovan.whitworth@gmail.com" %>
    <h3>Import Subcategories From Excel</h3>
    <%= form_tag import_subcategories_attractions_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import" %>
    <% end %>
    <br />
    <h3>Update from Excel File</h3>
    <%= form_tag import_update_attractions_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import" %>
    <% end %>
    <br />
  <% end %>

<% else %>
  <h3>You are not signed in or do not have the proper permissions to view this page</h3>
<% end %>
<link href="https://cdn.datatables.net/buttons/1.2.1/css/buttons.dataTables.min.css" type="text/css">

app/views/attractions/new.html.erb
<div class="container" data-controller='attractions' data-action="onload">
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being updated:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if user_signed_in? && (current_user.has_role?("publisher") || current_user.has_role?("editor") || current_user.admin?) %>
    <h2 class="top20">Create A New Attraction</h2>

    <%= simple_form_for @attraction, html: { role: 'form'} do |f| %>
      <div class="row">
        <div class="col-md-6">
          <p>
            <input id="pac-input" class="controls form-control" type="text"
              placeholder="Search For An Attraction">
          </p>
          <div id="map-canvas" style="height:500px;"></div>
        </div>
        <div class="col-md-6">
          <div class="form-group lat-lng">
            <div class="row">
              <div class="col-xs-12 col-sm-12"><%= f.input :display_address, placeholder: 'Address', :input_html => { "data-geo" => "formatted_address", class: 'longer-input form-control' }, label: "Display Address" %>
              </div>
              <div class="col-xs-12 col-sm-6"><%= f.input :latitude, :input_html => { "data-geo" => "lat", class: 'form-control' } %></div>
              <div class="col-xs-12 col-sm-6"><%= f.input :longitude, :input_html => { "data-geo" => "lng", class: 'form-control' } %></div>
              <div class="col-xs-12 col-sm-12"><%= f.input :street_number, :input_html => { "data-geo" => "street_number", class: 'form-control' } %></div>
              <div class="col-xs-12 col-sm-4"><%= f.input :route, :input_html => { "data-geo" => "route", class: 'form-control' } %></div>
              <div class="col-xs-12 col-sm-4"><%= f.input :sublocality, :input_html => { "data-geo" => "sublocality", class: 'form-control'} %></div>
              <div class="col-xs-12 col-sm-4"><%= f.input :locality, :input_html => { "data-geo" => "locality", class: 'form-control' } %></div>
              <div class="col-xs-12 col-sm-6"><%= f.input :state, :input_html => { "data-geo" => "administrative_area_level_1", class: 'form-control' } %></div>
              <div class="col-xs-12 col-sm-6"><%= f.input :post_code, as: :string, :input_html => { "data-geo" => "postal_code", class: 'form-control' } %></div>
              <div class="col-xs-12 col-sm-12"><%= f.input :phone_number, input_html: { "data-geo" => "formatted_phone_number", class: 'form-control' } %></div>
              <div class="col-xs-12 col-sm-12"><%= f.input :place_id, input_html: { "data-geo" => "place_id", class: 'form-control' }, label: "Google Place ID" %></div>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div>
          <%= f.check_box :footer_include, label: false %>&nbsp;Include In Footer?
      </div>
      <hr>
      <div class="form-group js-primary-category radio-inline" style="margin-left: -20px">
        <%= f.input :primary_category_id do %>
         <%= f.select :primary_category_id, @primary_categories.map { |category| [category.name, category.id] }%>
       <% end %>
      </div>
      <div class="form-group">
        <table class="table">
          <tr>
            <td>
          </tr>
        </table>
      </div>
      <div class="form-group">
        <%= f.input :display_name, input_html: { class: 'form-control' } %>
      </div>
      <div class="form-group">
      </div>
      <div class="form-group">
        <%= f.label "Parentable" %><br>
        <%= radio_button_tag 'parentable_chose', 'country', false %> Country &nbsp;&nbsp;
        <%= radio_button_tag 'parentable_chose', 'region', false %> Region &nbsp;&nbsp;
        <%= radio_button_tag 'parentable_chose', 'place', false %> Place &nbsp;&nbsp;
        <%= radio_button_tag 'parentable_chose', 'attraction', false %> Attraction &nbsp; &nbsp;
        <%= radio_button_tag 'parentable_chose', 'no_parent', true %> No Parent
        <br>
        <%= f.fields_for :parent, (@attraction.childrens.new()) do |fc| %>
          <div id='chosen_country' style="display:none;">
            <%= fc.select(:parentable_id, @countries.collect {|p_c| [ p_c.display_name, p_c.id ] }, :required => true) %>
            <%= fc.hidden_field(:parentable_type, class: 'place_parent_attributes_parentable_type_country', value: "Country") %>
          </div>
          <div id='chosen_region' style="display:none;">
            <%= fc.select(:parentable_id, @regions.collect {|p_c| [ p_c.display_name, p_c.id ] }, :required => true) %>
            <%= fc.hidden_field(:parentable_type, class: 'place_parent_attributes_parentable_type_region', value: "Region") %>
          </div>
          <div id='chosen_place' style="display:none;">
            <%= fc.select(:parentable_id, @places.collect {|p_c| [ p_c.display_name, p_c.id ] }, :required => true) %>
            <%= fc.hidden_field(:parentable_type, class: 'place_parent_attributes_parentable_type_place', value: "Place") %>
          </div>
          <div id='chosen_attraction' style="display:none;">
            <%= fc.select(:parentable_id, @attractions.collect {|p_c| [ p_c.display_name, p_c.id ] }, :required => true) %>
            <%= fc.hidden_field(:parentable_type, class: 'place_parent_attributes_parentable_type_attraction', value: "Attraction") %>
          </div>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.input :meta_description, label: "Meta Description (leave blank to auto-populate)", input_html: { class: 'form-control area-description-input' } %><br>
        <span id="shortDescriptionCharCount">0</span> characters entered. (255 max)<br>
      </div>
      <div class="form-group">
        <%= f.input :description, as: :bootsy, label: "Long description", input_html: { class: 'form-control area-description-input', col: 50 } %><br>
        <span id="descriptionCharCount">0</span> characters entered. (700 max)<br>
      </div>
      <div class="form-group">
        <%= f.input :email, input_html: { class: 'form-control' } %>
      </div>
      <div class="form-group">
        <%= f.input :website, input_html: { class: 'form-control' } %>
      </div>
      <% if current_user.has_role?("publisher") || current_user.try(:admin) %>
        <div class="form-group published-radio">
          <%= f.input :status, as: :select, collection: ["draft", "edited", "live", "removed"] %>
        </div>
      <% end %>
      <div class="field">
        <strong>Secondary categories</strong><br>
        <div class="row">
        <% @subcategories.each do |category| %>
            <% if category.category_type == "subcategory" %>
              <div class="col-md-3">
                <%= hidden_field_tag "attraction[subcategory_ids][]", nil%>
                <%= check_box_tag "attraction[subcategory_ids][]", category.id, @attraction.subcategory_ids.include?(category.id), id: dom_id(category) %>
                <%= label_tag dom_id(category), category.name %>
              </div>
          <% end %>
        <% end %>
        </div>
      </div>
      <div class="form-group">
        <br>
        <strong>Age Range</strong>
        <%= f.input :minimum_age, collection: 0..18, label: "From:", input_html: { class: 'form-control' } %>
        <%= f.input :maximum_age, collection: 0..18, label: "To:", input_html: { class: 'form-control' } %>
      </div>
      <div class="field js-primary-category">
        <br>
        <strong>Price categories</strong><br>
        <div class="row">
        <% @subcategories.each do |category| %>
            <% if category.category_type == "price" %>
              <div class="col-md-2">
                <%= hidden_field_tag "attraction[subcategory_ids][]", nil%>
                <%= check_box_tag "attraction[subcategory_ids][]", category.id, @attraction.subcategory_ids.include?(category.id), id: dom_id(category) %>
                <%= label_tag dom_id(category), category.name %>
              </div>
          <% end %>
        <% end %>
        </div>
      </div>
      <div class="field js-primary-category">
        <br>
        <strong>Accessibility</strong><br>
        <div class="row">
        <% @subcategories.each do |category| %>
            <% if category.category_type == "accessibility" %>
            <div class="col-md-3">
              <%= hidden_field_tag "attraction[subcategory_ids][]", nil%>
              <%= check_box_tag "attraction[subcategory_ids][]", category.id, @attraction.subcategory_ids.include?(category.id), id: dom_id(category) %>
              <%= label_tag dom_id(category), category.name %>
            </div>
          <% end %>
        <% end %>
        </div>
      </div>
      <div class="field js-primary-category">
        <br>
        <strong>Attraction visit duration</strong><br>
        <div class="row">
        <% @subcategories.each do |category| %>
            <% if category.category_type == "duration" %>
            <div class="col-md-2">
              <%= hidden_field_tag "attraction[subcategory_ids][]", nil%>
              <%= check_box_tag "attraction[subcategory_ids][]", category.id, @attraction.subcategory_ids.include?(category.id), id: dom_id(category) %>
              <%= label_tag dom_id(category), category.name %>
            </div>
          <% end %>
        <% end %>
        </div>
      </div>
      <div class="field js-primary-category">
        <br>
        <strong>Best time of day</strong><br>
        <div class="row">
        <% @subcategories.each do |category| %>
            <% if category.category_type == "optimum_time" %>
            <div class="col-md-2">
              <%= hidden_field_tag "attraction[subcategory_ids][]", nil%>
              <%= check_box_tag "attraction[subcategory_ids][]", category.id, @attraction.subcategory_ids.include?(category.id), id: dom_id(category) %>
              <%= label_tag dom_id(category), category.name %>
            </div>
          <% end %>
        <% end %>
        </div>
      </div>
      <div class="field js-primary-category">
        <br>
        <strong>Weather Conditions</strong><br>
        <% @subcategories.each do |category| %>
            <% if category.category_type == "weather" %>
            <%= hidden_field_tag "attraction[subcategory_ids][]", nil%>
            <%= check_box_tag "attraction[subcategory_ids][]", category.id, @attraction.subcategory_ids.include?(category.id), id: dom_id(category) %>
            <%= label_tag dom_id(category), category.name %><br/>
          <% end %>
        <% end %>
      </div>
      <div class="form-group js-primary-category">
        <br>
        <input type="checkbox" id="special-requirements-box">&nbsp;&nbsp;<strong>Special requirements?</strong> (Unchecking will delete text)
        <div class="js-special-requirements">
          <%= f.input :special_requirements, label: false, input_html: { class: 'form-control' } %>
        </div>
      </div>
      <div class="form-group">
        <%= f.button :submit, 'Submit' %>
      </div>
    <% end %>
    <hr>
  <% else %>
    <h2>You do not have sufficient privileges to view this page</h2>
    <%= link_to "Home", root_path %>
  <% end %>
  <p></p>
  <br>
  <p></p>
</div>

app/views/attractions/paginate_deals.js.erb
<% if instance_variable_get("@#{params[:resources]}").present? and params[:resources].present? %>
  $("div#<%= params[:resources] %>-list").append("<%= escape_javascript( render(partial:  params[:pagination_template].present?? params[:pagination_template] : "#{params[:resources]}_list", collection: instance_variable_get("@#{params[:resources]}"), as: params[:collection_object].present?? params[:collection_object].to_sym : params[:resources].singularize.to_sym )) %>");
  <% if last_page? instance_variable_get("@#{params[:resources]}") %>
    $("div#<%= params[:resources] %>-single-pagination-container").remove();
  <% else %>
    $("div#<%= params[:resources] %>-single-pagination-container").find("a.single-pagination").attr('href', "<%= paginate_deals_attraction_path(@attraction, "active_#{params[:resources]}" => instance_variable_get("@#{params[:resources]}").next_page, resources: params[:resources], pagination_template: params[:pagination_template] )%>" )
  <% end %>

<% end %>

app/views/attractions/seo_analysis.html.erb
<div class="container">
  <%= render "/attractions/admin_tabs" %>
  <%= render "/shared/seo_information" %>
</div>